pub enum Alert {
  CloseNotify = ffi::BR_ALERT_CLOSE_NOTIFY,
  UnexpectedMessage = ffi::BR_ALERT_UNEXPECTED_MESSAGE,
  BadRecordMac = ffi::BR_ALERT_BAD_RECORD_MAC,
  RecordOverflow = ffi::BR_ALERT_RECORD_OVERFLOW,
  DecompressionFailure = ffi::BR_ALERT_DECOMPRESSION_FAILURE,
  HandshakeFailure = ffi::BR_ALERT_HANDSHAKE_FAILURE,
  BadCertificate = ffi::BR_ALERT_BAD_CERTIFICATE,
  UnsupportedCertificate = ffi::BR_ALERT_UNSUPPORTED_CERTIFICATE,
  CertificateRevoked = ffi::BR_ALERT_CERTIFICATE_REVOKED,
  CertificateExpired = ffi::BR_ALERT_CERTIFICATE_EXPIRED,
  CertificateUnknown = ffi::BR_ALERT_CERTIFICATE_UNKNOWN,
  IllegalParameter = ffi::BR_ALERT_ILLEGAL_PARAMETER,
  UnknownCa = ffi::BR_ALERT_UNKNOWN_CA,
  AccessDenied = ffi::BR_ALERT_ACCESS_DENIED,
  DecodeError = ffi::BR_ALERT_DECODE_ERROR,
  DecryptError = ffi::BR_ALERT_DECRYPT_ERROR,
  ProtocolVersion = ffi::BR_ALERT_PROTOCOL_VERSION,
  InsufficientSecurity = ffi::BR_ALERT_INSUFFICIENT_SECURITY,
  InternalError = ffi::BR_ALERT_INTERNAL_ERROR,
  UserCanceled = ffi::BR_ALERT_USER_CANCELED,
  NoRenegotiation = ffi::BR_ALERT_NO_RENEGOTIATION,
  UnsupportedExtension = ffi::BR_ALERT_UNSUPPORTED_EXTENSION,
  NoApplicationProtocol = ffi::BR_ALERT_NO_APPLICATION_PROTOCOL,
}
